### ISSUE TITLE
Not supported on flutter 3.7.0  

### ISSUE THREAD

**Issue by tanmay-icreon** [Enough-Software/enough_giphy_flutter#1]
The library is not supported on flutter v3.7.0, as the library has a dependency on flutter_platform_widgets v1.11.1.

flutter_platform_widgets v1.11.1 is using RaisedButton, FlatButton which has been deprecated in Flutter v3.7.0!

`enough_giphy_flutter ^0.3.0 requires flutter_platform_widgets ^1.11.1.`

**Comment by robert-virkus** [comment]
Thanks for your report, I have now published `enough_giphy_flutter: ^0.4.0` that fixes the compatibily!
